appname: "PowerdnsTango"

layout: "main"

session: Storable
session_dir: /tmp/pdns_tango
session_expires: 3600

charset: "UTF-8"
template: "template_toolkit"
serializer: "JSON"

dns:
    additional_valid_tld: [nx, lan, test]
    soa_refresh_min: 1200
    soa_refresh_max: 43200
    soa_retry_min: 180
    soa_retry_max: 900
    soa_expire_min: 1209600
    soa_expire_max: 2419200
    soa_minimum_min: 3600
    soa_minimum_max: 10800
    soa_ttl_min: 3600
    soa_ttl_max: 4294967296

engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
  FlashMessage:
    token_name: flash
    session_hash_key: _flash
  Email:
    from: 'YOUR-FORM-EMAIL-ADDRESS'
    subject: 'Powerdns Tango'
    driver: smtp
    host: localhost
  Database:
    driver: 'YOUR-DATABASE-TYPE'
    database: 'YOUR-DATABASE-NAME'
    host: 'LOCATION-OF-DATABASE'
    port: DATABASE-PORT
    username: 'YOUR-DATABASE-USERNAME'
    password: 'YOUR-DATABASE-PASSWORD'
    connection_check_threshold: 10
    dbi_params:
    RaiseError: 1
    AutoCommit: 1
    log_queries: 1
